2025-04-26 00:10:02,389 - MoodMusicCurator - INFO - main.py:6 - Mood Music Curator Application started.
2025-04-26 00:10:02,391 - MoodMusicCurator - ERROR - main.py:12 - An unexpected error occurred: RealTimeFacialAnalyzer.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "C:\Users\peopl\Desktop\GenAI Project Data\mood_music_curator\mood_music_curator\main.py", line 9, in main
    analyzer = RealTimeFacialAnalyzer(logger)
TypeError: RealTimeFacialAnalyzer.__init__() takes 1 positional argument but 2 were given
